import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const header = (
    <header>
      <h1>CycleGears</h1>
      <ul>
        <li>About</li>
        <li>Collection</li>
        <li>Shop</li>
        <li>Service</li>
      </ul>
      <div>login/signup</div>
    </header>
  );

  const footer = <footer>All right's are reserved</footer>;
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  flex flex-col min-h-screen  `}
      >
        {header}
        <main className="flex-grow">{children}</main>
        {footer}
      </body>
    </html>
  );
}
